### PR TITLE
Travis CI support

### PR DESCRIPTION
**Pull request by robbiet480**
🚨 THIS NEEDS TO BE SQUASH AND MERGED 🚨

### CODE REVIEW

**Comment by robbiet480** [comment]
@mertenats Can you please enable Travis CI for your repo now? It's free! You should be able to get it going by going [here](https://travis-ci.org/mertenats/Arilux_AL-LC0X) and logging in. As soon as the repo is active the next push should run the tests. I test all RGB types, remote types, JSON defines, etc. It's only testing that everything compiles, not sure if it's possible to get the code itself tested past that. It will at least catch simple errors for us.

**Comment by SamZorSec** [comment]
@robbiet480 Done! Thanks. With your collaboration, I've learned a lot of new things ;-).

**Comment by robbiet480** [comment]
@mertenats Can you give me administrator on this repo for at least a few minutes so I can change some settings like enabling Travis on pull requests?

**Comment by SamZorSec** [comment]
@robbiet480 I'm looking for the option on Travis Cl, but I can't find it...

**Comment by robbiet480** [comment]
@mertenats No I mean admin on the GitHub repo. I already have admin on Travis since I have write access.

**Comment by SamZorSec** [comment]
@robbiet480 I can't give you the admin permissions on GitHub, only the collaborator status.

**Comment by robbiet480** [comment]
@mertenats Hm okay. If you go [here](https://github.com/mertenats/Arilux_AL-LC0X/settings/branches/master) you should be able to enable "Require status checks to pass before merging". Once that's enabled you should check the box labeled "Require branches to be up to date before merging" and finally the box labeled "continuous-integration/travis-ci". That's everything that I needed to do. Let me know if you have problems.

**Comment by SamZorSec** [comment]
@robbiet480 It's done. Thanks.

**Pull request merged**
