### PR TITLE
RGBW/RGBWW support, general fixes

### LINKED ISSUE #5: Support for RGBW?
Hi there,

I noticed there are also RGBW controllers:
http://www.banggood.com/ARILUX-AL-LC02-Super-Mini-LED-WIFI-APP-Controller-Dimmer-for-RGBW-LED-Strip-Light-DC-9-12V-p-1060222.html

would support be possible? :)

### PR DESCRIPTION
**Pull request by robbiet480**
Adds RGBW/RGBWW support thanks to @DanGunvald (originally proposed in #1). Also includes the following:

- MQTT last will and testament
- move configuration into its own file
- output unknown IR codes to serial/telnet
- some more general fixes

Closes #5

### CODE REVIEW

**Comment by SamZorSec** [comment]
@DanGunvald @robbiet480 Thanks for your amazing work!

**Comment by robbiet480** [comment]
@mertenats Don't go anywhere quite yet, got some more stuff coming in the next 10-20 minutes. :)

**Comment by robbiet480** [comment]
@mertenats Can you try out this latest code when you have a moment, specifically test out the color stuff? I think that color changing may have broken with this PR because it seems RGB is now reversed...

**Comment by KmanOz** [comment]
@robbiet480 You must hold the record for greatest number of contributions to HA related firmware / software surely by now LOL

**Comment by SamZorSec** [comment]
@robbiet480 Thanks again for the amazing work! I'm currently not at home until the end of the month, so I can't test it.

**Comment by robbiet480** [comment]
@mertenats Okay, will test more myself and try to figure out what went wrong...

**Comment by robbiet480** [comment]
@mertenats Fixed in 7596a4123f03ed2dd5f8a4f2fc51af254214a303. Wondering if the RGBWW pins are wrong too, I don't have one of those boards to test with :(

**Comment by DanGunvald** [comment]
I can verify the WW pins tonight, as I am using the lc08. I dont recall whether I am using the latest code.

**Comment by DanGunvald** [comment]
Pin setup for lc-08 is correct in current code(cloned 2017-03-07). RGBW needs to be defined for RGBWW to work. 
"#ifdef RGBW" in Arilux.cpp should be replaced with "#if defined(RGBW) || defined (RGBWW)" on order to remove the dependency og RGBW when choosing RGBWW.

**Comment by robbiet480** [comment]
Fixed RGBWW support, thanks @DanGunvald!

**Comment by ssolmaz** [comment]
I have a white led strip.
There is only + and - output.
Can I use LC04 (RGBW + IR).
Which channel I have to use. W? or R?

**Comment by DanGunvald** [comment]
It doesnt matter what you use if you set all channels to the desired level. LC04 should work.

**Comment by ssolmaz** [comment]
Thank you @DanGunvald
I bought LC04.
I will try.

**Pull request merged**
